### PR TITLE
[Fix]  Modify the use of rotated anchor inside flags

### PR DESCRIPTION
**Pull request by GamblerZSY**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Fix a bug in Rotated FasterRCNN-OBB.

## Modification
Change the rotated_anchor_inside_flags in the _get_targets_single function to anchor_inside_flags implemented in MMDetection.

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by zytx121** [comment]
Good job! Could you fix the same bug in OrientedRPNHead?

**Comment by GamblerZSY** [comment]
> Good job! Could you fix the same bug in OrientedRPNHead?

Ok, I will fix the same bug.

**Comment by yangxue0827** [comment]
Thank you for your contributions. Please follow https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to set pre-commit and fix the lint error.

**Comment by GamblerZSY** [comment]
> Thank you for your contributions. Please follow https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to set pre-commit and fix the lint error.

Ok, thanks for your instruction.

**Comment by GamblerZSY** [comment]
> Thank you for your contributions. Please follow https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to set pre-commit and fix the lint error.

Lint error has been fixed.

**Comment by GamblerZSY** [comment]
> Good job! Could you fix the same bug in OrientedRPNHead?

The same bug in OrientedRPNHead has been fixed.

**Review by zytx121 — APPROVED** [review]
LGTM

**Review by yangxue0827 — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
