### PR TITLE
[Docs] Fix typo in Config File and Model Zoo

### PR DESCRIPTION
**Pull request by nijkah**
## Motivation
Fix typo in config file and model zoo.

## Modification
Fix typo in config file and model zoo.

### CODE REVIEW

**Comment by zytx121** [comment]
Yes, It's my mistake. However, the typo should be `MS+RR` -> `MS`. And could you fix the same typo in `docs/zh_cn/model_zoo.md`? (no chinese in this part.)

**Comment by nijkah** [comment]
@zytx121 But in the [log](https://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_r50_fpn_1x_dota_ms_rr_le90/roi_trans_r50_fpn_1x_dota_ms_rr_le90_20220205_171729.log.json) it seems to use `PolyRandomRotate` in the config file.
The config file seems to have same data configuration as in [redet_re50_refpn_1x_dota_ms_rr_le90](https://download.openmmlab.com/mmrotate/v0.1.0/redet/redet_re50_fpn_1x_dota_ms_rr_le90/redet_re50_fpn_1x_dota_ms_rr_le90_20220206_105343.log.json).
Am I missing some points?

**Comment by zytx121** [comment]
> @zytx121 But in the [log](https://download.openmmlab.com/mmrotate/v0.1.0/roi_trans/roi_trans_r50_fpn_1x_dota_ms_rr_le90/roi_trans_r50_fpn_1x_dota_ms_rr_le90_20220205_171729.log.json) it seems to use `PolyRandomRotate` in the config file. The config file seems to have same data configuration as in [redet_re50_refpn_1x_dota_ms_rr_le90](https://download.openmmlab.com/mmrotate/v0.1.0/redet/redet_re50_fpn_1x_dota_ms_rr_le90/redet_re50_fpn_1x_dota_ms_rr_le90_20220206_105343.log.json). Am I missing some points?

You are right, it should be MS+RR.

**Comment by zytx121** [comment]
Could you fix the same typo in `/configs/roi_trans/README.md` and `docs/zh_cn/model_zoo.md`?

**Review by zytx121 — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
