### PR TITLE
[Fix] Fix test code for datasets

### PR DESCRIPTION
**Pull request by nijkah**
## Motivation
Although the test code for datasets doesn't require `CUDA_AVAILABLE`, the current code skips its test.
I fixed it.

## Modification
- Remove `pytest.mark.skipif`
- Fix floating point comparison

### CODE REVIEW

**Review by zytx121 — APPROVED** [review]
LGTM

**Comment by zytx121** [comment]
The lint failed on Windows. https://github.com/open-mmlab/mmrotate/runs/6057770448?check_suite_focus=true. Please check it.

**Comment by nijkah** [comment]
@zytx121 
I am so sorry, but how can I debug this? The error log just says 'the operation was canceled.'
Currently, I cannot figure out why it is stuck in testing `tests\test_data\test_datasets\test_dota.py` in `(windows-2022, 3.8, cu111)` while it succeed in `(windows-2022, 3.8, cpu)`.

**Comment by zytx121** [comment]
> @zytx121 I am so sorry, but how can I debug this? The error log just says 'the operation was canceled.' Currently, I cannot figure out why it is stuck in testing `tests\test_data\test_datasets\test_dota.py`, which doesn't require any CUDA operations, in `(windows-2022, 3.8, cu111)` while it succeeds in `(windows-2022, 3.8, cpu)`.

Maybe it's because when we do `from mmrotate.datasets.dota import DOTADataset`, we also do this `from mmcv.ops import nms_rotated`.  So we should need to modified the `mmrotate.datasets.dota`, change the position of `from mmcv.ops import nms_rotated`.

**Comment by nijkah** [comment]
But, I'm still not sure. The test code succeeded in `(windows-2022, 3.8, cpu)`. Is it related to `nms_rotated` really?

**Comment by zytx121** [comment]
You are right. I will check it.

**Comment by zytx121** [comment]
This is a little strange. Can it pass CI before removing `pytest.mark.skipif`? But it failed in the GPU environment. Lol.

**Comment by zytx121** [comment]
Oh, I make a mistake. If we use `pytest.mark.skipif`, this test unit will not be run, because there is no GPU in Github Action.

**Comment by nijkah** [comment]
@zytx121 It works after recovering `pytest.mark.skipif`. :(

**Comment by zytx121** [comment]
I guess I find the true reason.
image

**Comment by zytx121** [comment]
@nijkah 
I find I found a solution finally! You can refer to #256 

WeChat1daf9ea72e92516ca2b4cdddc34a44c4

**Comment by nijkah** [comment]
@zytx121 Thank you for your work and solution!
BTW, I still cannot understand why the previous setting could not run. 😞

**Comment by nijkah** [comment]
Then, may I wait for your PR to merge, or update it in this PR?

**Comment by zytx121** [comment]
Because mmrotate relies on mmdet, mmdet cannot work normally in the win-py3.8-cu111 environment. I looked at mmocr, which relies on mmdet too, and found that they use win-py3.7-cu102. https://github.com/open-mmlab/mmocr/blob/main/.github/workflows/pr_stage_test.yml

**Comment by zytx121** [comment]
You could update it in this PR.

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
