### PR TITLE
[Feature] Allow turn-off filter_empty_gt

### LINKED ISSUE #244: Does MMrotate support  pure background images without ground truths to participate in training?
In the definitions of DOTA and HRSC dataset class, function “**_filter_imgs**” filter images without ground truths. 
I expect to use “**filter_ empty_ gt=False**” in the config to get pure background images to participate in the training, just like coco dataset in MMdet. But it is not worked. What should I do to avoid “_filter_imgs”?

### PR DESCRIPTION
**Pull request by nijkah**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Please describe the motivation of this PR and the goal you want to achieve through this PR.
closes #244 

## Modification
Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by nijkah** [comment]
Should I add a new test image with empty gts for the unit test?

**Comment by ZwwWayne** [comment]
> Should I add a new test image with empty gts for the unit test?

It would be much better if the UT is enhanced.

**Review by zytx121 — APPROVED** [review]
LGTM.

**Comment by nijkah** [comment]
@zytx121 I found that the previous code does not work. I fixed it and add a unit test.

**Review by jbwang1997 — APPROVED** [review]
LGTM

**Review by zytx121 — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
