### PR TITLE
[Fix] Bug for SASM durning training.

### PR DESCRIPTION
**Pull request by lalalagogogochong**
1.assign函数参数顺序错误，overlaps参数位置错误（这个问题不影响正常训练，是我调试的时候发现的，你们可以确认一下，这个有没响）
2.all_overlaps_rotate_list之前大小固定为4，应该按照一个batchsize大小进行设置，修改之后不会报tensor维度错误，可以正常训练
（修改了lint错误，重新提交一次）

### CODE REVIEW

**Comment by yangxue0827** [comment]
Solution for https://github.com/open-mmlab/mmrotate/issues/94

**Comment by yangxue0827** [comment]
If you can successfully reproduce and get normal performance, please feedback here, thank you.

**Comment by zytx121** [comment]
Hi @lalalagogogochong 
Thanks for your PR. However, it is also problematic to modify the parameter position in this way. Because the parameter positions of `MaxConvexIoUAssigner` and `ConvexAssigner` are different, it is recommended to make another judgment.
But I think ConvexAssigner is only used for `init assigner`, MaxConvexIoUAssigner is only used for `refine assigner`. So actually only need to modify the parameter position of the `init assigner`.

**Comment by lalalagogogochong** [comment]
> Hi @lalalagogogochong Thanks for your PR. However, it is also problematic to modify the parameter position in this way. Because the parameter positions of `MaxConvexIoUAssigner` and `ConvexAssigner` are different, it is recommended to make another judgment. But I think ConvexAssigner is only used for `init assigner`, MaxConvexIoUAssigner is only used for `refine assigner`. So actually only need to modify the parameter position of the `init assigner`.

Yes, I think wrong. I'll revise it

**Review by zytx121 — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Comment by OpenMMLab-gd** [comment]
Hi @lalalagogogochong！First of all, we want to express our gratitude for your significant PR in the MMRotate project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/raweFPmdzG

If you are Chinese or have WeChat，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤ @lalalagogogochong

**Pull request merged**
