### PR TITLE
[Feature] add codes for inference speed statistics

### PR DESCRIPTION
**Pull request by heiyuxiaokai**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
1. add codes for inference speed statistics from https://github.com/open-mmlab/mmdetection
2. fix the bug in eval_map

## Modification
Please briefly describe what modification is made in this PR.

## BC-breaking (Optional)
Does the modification introduce changes that break the back-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)
If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by yangxue0827** [comment]
This branch has conflicts that must be resolved

Conflicting files: 
mmrotate/datasets/dota.py

You need to download the dev branch and then submit the corresponding PR.
In addition, you need to add detailed docstring to all functions, you can refer to other scripts.

**Comment by heiyuxiaokai** [comment]
The inference speed of fp16 is about 1.5 times the speed of fp32 with a V100-SXM2-16GB. Here the gpu infos,
- FP16 (half) performance: 31.33 TFLOPS (2:1)
- FP32 (float) performance: 15.67 TFLOPS
- FP64 (double) performance: 7.834 TFLOPS (1:2)
It seems not to reach the limit.

**Comment by heiyuxiaokai** [comment]
> This branch has conflicts that must be resolved
> 
> Conflicting files: mmrotate/datasets/dota.py
> 
> You need to clone the dev branch and then submit the corresponding PR. In addition, you need to add detailed docstring to all functions, you can refer to other scripts.

ok

**Comment by yangxue0827** [comment]
Thank you for your contributions. Please follow https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md to set pre-commit and fix the lint error.

**Comment by yangxue0827** [comment]
All checks have passed, looking forward to the addition of the docstring.

**Review by yangxue0827 — APPROVED** [review]
LGTM

**Review by jbwang1997 — APPROVED** [review]
LGTM

**Review by zytx121 — APPROVED** [review]
LGTM

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
